/*
 * The line's marks as a module a component can draw from.
 *
 * The masters are SVG files, committed under `assets/marks/` and shipped as
 * files in `dist/marks/` for whatever cannot run React - a favicon step, a
 * native window icon. A React component cannot import an SVG file the same way
 * in every consumer's bundler, so the same masters are also written out as
 * markup strings in `packages/dowel/src/marks.ts`. That module is generated
 * from the files and the release gate regenerates it and compares, so the two
 * cannot drift.
 *
 * Only the inside of each file is kept: the component draws its own `<svg>`
 * at the size it is asked for. The one id in the masters - the gradient of a
 * two-colour mark - is document-global in SVG, and two marks on one screen
 * would share it; it becomes a `{{id}}` placeholder the component fills with a
 * per-instance id.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'

/** The three levels, smallest size each is drawn at, from the line's rule. */
export const LEVELS = ['L', 'M', 'S']

/** Every mark in a directory of masters: name -> level -> inner markup. */
export function readMarks(dir) {
  const marks = {}
  for (const file of readdirSync(dir).sort()) {
    const match = /^(.+)-([LMS])\.svg$/.exec(file)
    if (!match) continue
    const [, name, level] = match
    const source = readFileSync(resolve(dir, file), 'utf8').trim()
    const inner = /^<svg\b[^>]*viewBox="0 0 100 100"[^>]*>([\s\S]*)<\/svg>$/.exec(source)
    if (!inner) throw new Error(`${file} is not a mark master: expected one <svg> on the 0 0 100 100 grid`)
    const body = inner[1]
      .replace(/\s*\n\s*/g, ' ')
      .replace(/id="pair"/g, 'id="{{id}}"')
      .replace(/url\(#pair\)/g, 'url(#{{id}})')
    if (/\bid="(?!\{\{id\}\})/.test(body)) throw new Error(`${file} carries an id this module does not rename`)
    ;(marks[name] ??= {})[level] = body
  }
  for (const [name, levels] of Object.entries(marks)) {
    for (const level of LEVELS) {
      if (!levels[level]) throw new Error(`${name} has no ${level} master`)
    }
  }
  return marks
}

/** The TypeScript module, as text. */
export function renderMarksModule(dir) {
  const marks = readMarks(dir)
  const entries = Object.entries(marks)
    .map(
      ([name, levels]) =>
        `  ${JSON.stringify(name)}: {\n${LEVELS.map((level) => `    ${level}: ${JSON.stringify(levels[level])},`).join('\n')}\n  },`,
    )
    .join('\n')
  const names = Object.keys(marks)
    .map((name) => `  | '${name}'`)
    .join('\n')
  return `// Generated by tools/import-marks.mjs from assets/marks/ - do not edit.
/*
 * The marks of the lacodda line, as markup a component draws inside its own
 * \`<svg viewBox="0 0 100 100">\`. \`{{id}}\` stands for the gradient id of a
 * two-colour mark and must be replaced per instance.
 *
 * Three levels, by the size the mark is drawn at: L at 64px and up carries the
 * metaphor, M from 28 to 63 is the code alone, S at 27 and under is the tile
 * filled with the product's colour.
 */

/** One product's mark at each of its three levels. */
export interface MarkLevels {
  readonly L: string
  readonly M: string
  readonly S: string
}

/** Every mark there is: each product of the line, and \`lacodda\` for the line. */
export type MarkName =
${names}

/** The level a mark is drawn at, for a size in CSS pixels. */
export function markLevel(size: number): keyof MarkLevels {
  if (size >= 64) return 'L'
  if (size >= 28) return 'M'
  return 'S'
}

export const marks: Readonly<Record<MarkName, MarkLevels>> = {
${entries}
}
`
}
